name: 'Auto Assign PR Reviewer & Assignee'
description: 'PR 리뷰어와 담당자를 자동으로 지정합니다.'
inputs:
  configuration-path:
    description: 'The path to the configuration file.'
    required: true
runs:
  using: 'node20'
  main: 'dist/main.js'
