name: [TeamName] Auto Assign PR Reviewer & Assignee

on:
  pull_request:
    branches:
      - main
    types: [ opened, ready_for_review ]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Assign PR Reviewer & Assignee
        uses: SeongHo5/pr-buddy@v1.0
        with:
          config: .github/auto-assign.yml
