name: Assign PR Reviewer & Assignee

on:
  pull_request:
    branches:
      - main
    types: [ opened, ready_for_review ]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR Reviewer & Assignee
        uses: SeongHo5/auto-assign-pr@v0.0.3
        with:
          configuration-path: .github/auto-assign.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN }}
